/** Fallback format headers when API doesn't return them (e.g. backend not running) */
export const UPLOADER_FORMAT_HEADERS: Record<string, string[]> = {
  bcase: [
    'store code',
    'store name',
    'month',
    'space - carpet area (sq ft)',
    'sales/ sq ft (rs/ day)',
    'sales/ sq ft (rs/ month)',
    'gmv softlines l',
    'gmv hardlines l',
    'total gmv l',
    'net revenue total',
    'net revenue sl',
    'net revenue hl',
    'pm%',
    'pm total',
    'pm sl',
    'pm hl',
    'staff cost',
    'rent + cam',
    'cam',
    'supply chain costs',
    'total opex',
    'cm l',
    'cm%',
    'monetisation',
    'marketing l',
    'cm2 l',
    'cm2%',
    'site capex (with tax)',
    'total capex',
    'total capex with interest',
  ],
};
